# Generated by Django 4.0 on 2021-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField()),
                ('command', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fireplace',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField()),
                ('ip', models.CharField(max_length=20)),
                ('block', models.BooleanField()),
                ('state', models.SmallIntegerField()),
                ('language', models.SmallIntegerField()),
                ('fuel_level', models.IntegerField()),
                ('fire_level', models.IntegerField()),
                ('favorite_mode', models.IntegerField()),
                ('temp_tank', models.IntegerField()),
                ('temp_ten', models.IntegerField()),
                ('temp_burner', models.IntegerField()),
            ],
        ),
    ]
